language: objective-c
osx_image: xcode9.2

before_script:
    - ./build_environment.sh

script:
    - xcodebuild clean build test -sdk iphonesimulator -workspace SuperheroApp.xcworkspace -scheme SuperheroApp  CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.2'
